### PR TITLE
Remove all tests that require an internet connexion

### PR DESCRIPTION
**Pull request by mbovel**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
This is not how we update the community build. We need to push a branch with the fix to this repo and change the lampeplf/dotty community build submodule to point to that commit. We should also not delete the files. We should comment them out and add a comment (`/* ... */`), this way we can take upstream changes without conflicts.

**Comment by nicolasstucki** [comment]
Disabling those two tests seems good.

**Comment by mbovel** [comment]
Okay, branch updated with tests commented out.

If it looks okay to you, could you push this commit to a branch (or give me the needed rights to do so)?

**Comment by mbovel** [comment]
PR opened to the `increse-timeout` branch: #2.

**Pull request closed without merging**
